#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Apr 19 10:32:11 EDT 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fir_tb_behav -key {Behavioral:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -view /home/ubuntu/2025_implementation_project/lab03/sim/fir_vvd/axi_stream.wcfg -view /home/ubuntu/2025_implementation_project/lab03/sim/fir_vvd/axi_lite.wcfg -view /home/ubuntu/2025_implementation_project/lab03/sim/fir_vvd/data_calculation.wcfg -log simulate.log"
xsim fir_tb_behav -key {Behavioral:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -view /home/ubuntu/2025_implementation_project/lab03/sim/fir_vvd/axi_stream.wcfg -view /home/ubuntu/2025_implementation_project/lab03/sim/fir_vvd/axi_lite.wcfg -view /home/ubuntu/2025_implementation_project/lab03/sim/fir_vvd/data_calculation.wcfg -log simulate.log

